VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END

Attribute VB_Name = "ICRFVars"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Description = "Interface of CRF Variables"

'@Folder("Linelist")
'@ModuleDescription("Interface of CRF Variables")
'@IgnoreModule UseMeaningfulName, HungarianNotation

Option Explicit

Public Sub WriteInfo(): End Sub