VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IDesignerLog"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Description = "Interface of Designer logging"

'@IgnoreModule UseMeaningfulName, HungarianNotation

'@Folder("General")
'@ModuleDescription("Interface of Designer logging")

Option Explicit

'Exposed methods

