VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END

Attribute VB_Name = "CRFChoices"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_Description = "Create and format CRF group of choices"

'@Folder("Dictionary")
'@ModuleDescription("Create and format CRF group of choices")
'@IgnoreModule UseMeaningfulName, HungarianNotation

Option Explicit
Implements ICRFChoices

Private Type TCRFChoi

End Type

Private this As TCRFChoi

Public Function 
