VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IAnalysis"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Description = "Interface of analysis class"

'@Interface
'@Folder("Analysis")
'@ModuleDescription("Interface of analysis class")
'@IgnoreModule ProcedureNotUsed

Option Explicit

'Exposed methods
Public Sub AddRows()
End Sub

Public Sub RemoveRows()
End Sub
