VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "EventMasterSetup"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Attribute VB_Description = "Implementation for managing Master Setup event handling"

'@PredeclaredId
'@Folder("MasterSetup")
'@ModuleDescription("Implementation for managing Master Setup event handling")

Option Explicit

Implements IEventMasterSetup
