VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END

Attribute VB_Name = "ILinelistCRF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Description = "Interface of LinelistCRF"

'@Folder("Dictionary")
'@ModuleDescription("Interface of LinelistCRF")
'@IgnoreModule UseMeaningfulName, HungarianNotation

Option Explicit

Public Sub Build(): End Sub